/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package skydrop.view;
import java.awt.Image;
import javax.swing.*;
import skydrop.database.DbConnection;
import skydrop.userDAO.PostDao;
import java.sql.*;
import java.util.ArrayList;
import java.util.List;


/**
 *
 * @author Suresh
 */
public class AdminProductEdit extends javax.swing.JFrame {
    
    private int id;
    
    public void setID(int id){
        this.id = id;
    }
    
    private int placeHolder = 1;

    PostDao postDao = new PostDao();
    /**
     * Creates new form ProductPageView
     */
    public AdminProductEdit() {
        initComponents();
        displayAllProducts();
        highlowbox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                displayAllProducts();
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        SearchButton = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        Search = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        Mcheckbox = new javax.swing.JCheckBox();
        Fcheckbox = new javax.swing.JCheckBox();
        Kcheckbox = new javax.swing.JCheckBox();
        jLabel5 = new javax.swing.JLabel();
        highlowbox = new javax.swing.JComboBox<>();
        ProductScrollPane = new javax.swing.JScrollPane();
        productGridPanel = new javax.swing.JPanel();
        male1 = new javax.swing.JPanel();
        delete1 = new javax.swing.JButton();
        image1 = new javax.swing.JLabel();
        category1 = new javax.swing.JLabel();
        price1 = new javax.swing.JLabel();
        name1 = new javax.swing.JLabel();
        male4 = new javax.swing.JPanel();
        delete2 = new javax.swing.JButton();
        image2 = new javax.swing.JLabel();
        category2 = new javax.swing.JLabel();
        price2 = new javax.swing.JLabel();
        name2 = new javax.swing.JLabel();
        male5 = new javax.swing.JPanel();
        delete3 = new javax.swing.JButton();
        image3 = new javax.swing.JLabel();
        category3 = new javax.swing.JLabel();
        price3 = new javax.swing.JLabel();
        name3 = new javax.swing.JLabel();
        male6 = new javax.swing.JPanel();
        delete4 = new javax.swing.JButton();
        image4 = new javax.swing.JLabel();
        category4 = new javax.swing.JLabel();
        price4 = new javax.swing.JLabel();
        name4 = new javax.swing.JLabel();
        male7 = new javax.swing.JPanel();
        delete5 = new javax.swing.JButton();
        image5 = new javax.swing.JLabel();
        category5 = new javax.swing.JLabel();
        price5 = new javax.swing.JLabel();
        name5 = new javax.swing.JLabel();
        male8 = new javax.swing.JPanel();
        delete6 = new javax.swing.JButton();
        image6 = new javax.swing.JLabel();
        category6 = new javax.swing.JLabel();
        price6 = new javax.swing.JLabel();
        name6 = new javax.swing.JLabel();
        male9 = new javax.swing.JPanel();
        delete7 = new javax.swing.JButton();
        image7 = new javax.swing.JLabel();
        category7 = new javax.swing.JLabel();
        price7 = new javax.swing.JLabel();
        name7 = new javax.swing.JLabel();
        male10 = new javax.swing.JPanel();
        delete8 = new javax.swing.JButton();
        image8 = new javax.swing.JLabel();
        category8 = new javax.swing.JLabel();
        price8 = new javax.swing.JLabel();
        name8 = new javax.swing.JLabel();
        male11 = new javax.swing.JPanel();
        delete9 = new javax.swing.JButton();
        image9 = new javax.swing.JLabel();
        category9 = new javax.swing.JLabel();
        price9 = new javax.swing.JLabel();
        name9 = new javax.swing.JLabel();
        btnback = new javax.swing.JButton();
        btnNext = new javax.swing.JButton();
        btnprevious = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setText("SkyDrop");

        SearchButton.setText("🔍");
        SearchButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        SearchButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SearchButtonActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        jLabel3.setText(" Your Smart Shopping Partner");

        Search.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SearchActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(jLabel1))
                .addGap(321, 321, 321)
                .addComponent(Search, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(SearchButton, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(SearchButton, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Search, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(16, 16, 16))
        );

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel4.setText("Categories");

        Mcheckbox.setText("Male");
        Mcheckbox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                McheckboxActionPerformed(evt);
            }
        });

        Fcheckbox.setText("Female");
        Fcheckbox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FcheckboxActionPerformed(evt);
            }
        });

        Kcheckbox.setText("Kids");
        Kcheckbox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                KcheckboxActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Mcheckbox, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Fcheckbox, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Kcheckbox, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(Mcheckbox)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Fcheckbox)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Kcheckbox))
        );

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel5.setText("Price Range");

        highlowbox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Higher to Lower", "Lower to Higher", " " }));
        highlowbox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                highlowboxActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(highlowbox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel5)
                    .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addContainerGap(57, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(highlowbox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(250, Short.MAX_VALUE))
        );

        ProductScrollPane.setViewportView(null);

        productGridPanel.setLayout(new java.awt.GridLayout(0, 3, 20, 20));

        male1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        delete1.setText("Delete");
        delete1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                delete1ActionPerformed(evt);
            }
        });
        male1.add(delete1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 241, -1, -1));
        male1.add(image1, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 6, 161, 149));

        category1.setText("men");
        male1.add(category1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 200, 40, -1));

        price1.setText("price");
        male1.add(price1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 200, -1, -1));

        name1.setText("name");
        male1.add(name1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 170, -1, -1));

        productGridPanel.add(male1);

        male4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        delete2.setText("Delete");
        delete2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                delete2ActionPerformed(evt);
            }
        });
        male4.add(delete2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 241, -1, -1));
        male4.add(image2, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 6, 161, 149));

        category2.setText("men");
        male4.add(category2, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 200, 40, -1));

        price2.setText("price");
        male4.add(price2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 200, -1, -1));

        name2.setText("name");
        male4.add(name2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 170, -1, -1));

        productGridPanel.add(male4);

        male5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        delete3.setText("Delete");
        delete3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                delete3ActionPerformed(evt);
            }
        });
        male5.add(delete3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 241, -1, -1));
        male5.add(image3, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 6, 161, 149));

        category3.setText("men");
        male5.add(category3, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 200, 40, -1));

        price3.setText("price");
        male5.add(price3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 200, -1, -1));

        name3.setText("name");
        male5.add(name3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 170, -1, -1));

        productGridPanel.add(male5);

        male6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        delete4.setText("Delete");
        delete4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                delete4ActionPerformed(evt);
            }
        });
        male6.add(delete4, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 241, -1, -1));
        male6.add(image4, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 6, 161, 149));

        category4.setText("men");
        male6.add(category4, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 200, 40, -1));

        price4.setText("price");
        male6.add(price4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 200, -1, -1));

        name4.setText("name");
        male6.add(name4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 170, -1, -1));

        productGridPanel.add(male6);

        male7.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        delete5.setText("Delete");
        delete5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                delete5ActionPerformed(evt);
            }
        });
        male7.add(delete5, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 241, -1, -1));
        male7.add(image5, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 6, 161, 149));

        category5.setText("men");
        male7.add(category5, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 200, 40, -1));

        price5.setText("price");
        male7.add(price5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 200, -1, -1));

        name5.setText("name");
        male7.add(name5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 170, -1, -1));

        productGridPanel.add(male7);

        male8.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        delete6.setText("Delete");
        delete6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                delete6ActionPerformed(evt);
            }
        });
        male8.add(delete6, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 241, -1, -1));
        male8.add(image6, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 6, 161, 149));

        category6.setText("men");
        male8.add(category6, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 200, 40, -1));

        price6.setText("price");
        male8.add(price6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 200, -1, -1));

        name6.setText("name");
        male8.add(name6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 170, -1, -1));

        productGridPanel.add(male8);

        male9.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        delete7.setText("Delete");
        delete7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                delete7ActionPerformed(evt);
            }
        });
        male9.add(delete7, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 241, -1, -1));
        male9.add(image7, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 6, 161, 149));

        category7.setText("men");
        male9.add(category7, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 200, 40, -1));

        price7.setText("price");
        male9.add(price7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 200, -1, -1));

        name7.setText("name");
        male9.add(name7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 170, -1, -1));

        productGridPanel.add(male9);

        male10.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        delete8.setText("Delete");
        delete8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                delete8ActionPerformed(evt);
            }
        });
        male10.add(delete8, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 241, -1, -1));
        male10.add(image8, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 6, 161, 149));

        category8.setText("men");
        male10.add(category8, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 200, 40, -1));

        price8.setText("price");
        male10.add(price8, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 200, -1, -1));

        name8.setText("name");
        male10.add(name8, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 170, -1, -1));

        productGridPanel.add(male10);

        male11.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        delete9.setText("Delete");
        delete9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                delete9ActionPerformed(evt);
            }
        });
        male11.add(delete9, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 241, -1, -1));
        male11.add(image9, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 6, 161, 149));

        category9.setText("men");
        male11.add(category9, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 200, 40, -1));

        price9.setText("price");
        male11.add(price9, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 200, -1, -1));

        name9.setText("name");
        male11.add(name9, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 170, -1, -1));

        productGridPanel.add(male11);

        ProductScrollPane.setViewportView(productGridPanel);

        btnback.setText("Back");
        btnback.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnbackActionPerformed(evt);
            }
        });

        btnNext.setText("Next");
        btnNext.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNextActionPerformed(evt);
            }
        });

        btnprevious.setText("previous");
        btnprevious.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnpreviousActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnback))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnprevious)
                        .addGap(431, 431, 431)
                        .addComponent(btnNext))
                    .addComponent(ProductScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 578, javax.swing.GroupLayout.PREFERRED_SIZE)))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(ProductScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnback)
                    .addComponent(btnNext)
                    .addComponent(btnprevious))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void SearchButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SearchButtonActionPerformed
        displayAllProducts();  
    }//GEN-LAST:event_SearchButtonActionPerformed

    private void McheckboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_McheckboxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_McheckboxActionPerformed

    private void delete1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_delete1ActionPerformed
        
    }//GEN-LAST:event_delete1ActionPerformed

    private void btnbackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnbackActionPerformed
        this.dispose();
        AdminView adminView = new AdminView();
                adminView.setId(id);
                adminView.setVisible(true);
    }//GEN-LAST:event_btnbackActionPerformed

    private void FcheckboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FcheckboxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_FcheckboxActionPerformed

    private void KcheckboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_KcheckboxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_KcheckboxActionPerformed

    private void SearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SearchActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SearchActionPerformed

    private void delete2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_delete2ActionPerformed
        
    }//GEN-LAST:event_delete2ActionPerformed

    private void delete3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_delete3ActionPerformed
        
    }//GEN-LAST:event_delete3ActionPerformed

    private void delete4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_delete4ActionPerformed
        
    }//GEN-LAST:event_delete4ActionPerformed

    private void delete5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_delete5ActionPerformed
        
    }//GEN-LAST:event_delete5ActionPerformed

    private void delete6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_delete6ActionPerformed
        
    }//GEN-LAST:event_delete6ActionPerformed

    private void delete7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_delete7ActionPerformed
        
    }//GEN-LAST:event_delete7ActionPerformed

    private void delete8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_delete8ActionPerformed
        
    }//GEN-LAST:event_delete8ActionPerformed

    private void delete9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_delete9ActionPerformed
        
    }//GEN-LAST:event_delete9ActionPerformed

    private void btnNextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNextActionPerformed
        this.placeHolder = placeHolder + 1;
        displayAllProducts();
    }//GEN-LAST:event_btnNextActionPerformed

    private void btnpreviousActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnpreviousActionPerformed
        this.placeHolder = placeHolder - 1;
        displayAllProducts();
    }//GEN-LAST:event_btnpreviousActionPerformed

    private void highlowboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_highlowboxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_highlowboxActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdminProductEdit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdminProductEdit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdminProductEdit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdminProductEdit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdminProductEdit().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox Fcheckbox;
    private javax.swing.JCheckBox Kcheckbox;
    private javax.swing.JCheckBox Mcheckbox;
    private javax.swing.JScrollPane ProductScrollPane;
    private javax.swing.JTextField Search;
    private javax.swing.JButton SearchButton;
    private javax.swing.JButton btnNext;
    private javax.swing.JButton btnback;
    private javax.swing.JButton btnprevious;
    private javax.swing.JLabel category1;
    private javax.swing.JLabel category2;
    private javax.swing.JLabel category3;
    private javax.swing.JLabel category4;
    private javax.swing.JLabel category5;
    private javax.swing.JLabel category6;
    private javax.swing.JLabel category7;
    private javax.swing.JLabel category8;
    private javax.swing.JLabel category9;
    private javax.swing.JButton delete1;
    private javax.swing.JButton delete2;
    private javax.swing.JButton delete3;
    private javax.swing.JButton delete4;
    private javax.swing.JButton delete5;
    private javax.swing.JButton delete6;
    private javax.swing.JButton delete7;
    private javax.swing.JButton delete8;
    private javax.swing.JButton delete9;
    private javax.swing.JComboBox<String> highlowbox;
    private javax.swing.JLabel image1;
    private javax.swing.JLabel image2;
    private javax.swing.JLabel image3;
    private javax.swing.JLabel image4;
    private javax.swing.JLabel image5;
    private javax.swing.JLabel image6;
    private javax.swing.JLabel image7;
    private javax.swing.JLabel image8;
    private javax.swing.JLabel image9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel male1;
    private javax.swing.JPanel male10;
    private javax.swing.JPanel male11;
    private javax.swing.JPanel male4;
    private javax.swing.JPanel male5;
    private javax.swing.JPanel male6;
    private javax.swing.JPanel male7;
    private javax.swing.JPanel male8;
    private javax.swing.JPanel male9;
    private javax.swing.JLabel name1;
    private javax.swing.JLabel name2;
    private javax.swing.JLabel name3;
    private javax.swing.JLabel name4;
    private javax.swing.JLabel name5;
    private javax.swing.JLabel name6;
    private javax.swing.JLabel name7;
    private javax.swing.JLabel name8;
    private javax.swing.JLabel name9;
    private javax.swing.JLabel price1;
    private javax.swing.JLabel price2;
    private javax.swing.JLabel price3;
    private javax.swing.JLabel price4;
    private javax.swing.JLabel price5;
    private javax.swing.JLabel price6;
    private javax.swing.JLabel price7;
    private javax.swing.JLabel price8;
    private javax.swing.JLabel price9;
    private javax.swing.JPanel productGridPanel;
    // End of variables declaration//GEN-END:variables
   


    
    

    
private void displayAllProducts() {
    clearAllProductPanels();

    String searchText = Search.getText().trim().toLowerCase();
    boolean showMale = Mcheckbox.isSelected();
    boolean showFemale = Fcheckbox.isSelected();
    boolean showKids = Kcheckbox.isSelected();
    boolean anyCategorySelected = showMale || showFemale || showKids;

    List<Integer> filteredProductIDs = new ArrayList<>();
    List<Integer> allProductIDs = postDao.getAdminProductIDs(id);

    
    for (Integer productId : postDao.getAdminProductIDs(id)) {
        String name = postDao.getProductNameDB(productId);
        String category = postDao.getProductCategoryDB(productId);

        if (!searchText.isEmpty() && !name.toLowerCase().contains(searchText)) {
            continue;
        }

        if (anyCategorySelected) {
            boolean matchesCategory =
                    (showMale && category.equalsIgnoreCase("male")) ||
                    (showFemale && category.equalsIgnoreCase("female")) ||
                    (showKids && category.equalsIgnoreCase("kids"));

            if (!matchesCategory) continue;
        }

        filteredProductIDs.add(productId);
    }
    String priceSortOrder = (String) highlowbox.getSelectedItem();
        if (priceSortOrder != null && !priceSortOrder.trim().isEmpty()) {
            filteredProductIDs.sort((id1, id2) -> {
                int price1 = postDao.getProductPriceDB(id1);
                int price2 = postDao.getProductPriceDB(id2);

                if (priceSortOrder.equalsIgnoreCase("Higher to Lower")) {
                    return Integer.compare(price2, price1); 
                } else if (priceSortOrder.equalsIgnoreCase("Lower to Higher")) {
                    return Integer.compare(price1, price2); 
                } else {
                    return 0; 
                }
            });
        }


    int productsPerPage = 9;
    int totalPages = (int) Math.ceil((double) filteredProductIDs.size() / productsPerPage);

    if (placeHolder < 0) placeHolder = 0;
    if (totalPages > 0 && placeHolder >= totalPages) placeHolder = totalPages - 1;
    if (totalPages == 0) placeHolder = 0; 

    int startIndex = placeHolder * productsPerPage;
    int endIndex = Math.min(startIndex + productsPerPage, filteredProductIDs.size());

    int displayedCount = 0;
    for (int i = startIndex; i < endIndex; i++) {
        int productId = filteredProductIDs.get(i);
        displayProduct(displayedCount, productId);
        displayedCount++;
    }
}    

private void clearAllProductPanels() {
    clearProductPanel(male1, name1, price1, category1, image1);
    clearProductPanel(male4, name2, price2, category2, image2);
    clearProductPanel(male5, name3, price3, category3, image3);
    clearProductPanel(male6, name4, price4, category4, image4);
    clearProductPanel(male7, name5, price5, category5, image5);
    clearProductPanel(male8, name6, price6, category6, image6);
    clearProductPanel(male9, name7, price7, category7, image7);
    clearProductPanel(male10, name8, price8, category8, image8);
    clearProductPanel(male11, name9, price9, category9, image9);
}

private void displayProduct(int index, int productId) {
    String name = postDao.getProductNameDB(productId);
    int price = postDao.getProductPriceDB(productId);
    String category = postDao.getProductCategoryDB(productId);
    Image image = postDao.displayImageFromDatabase(productId);

    JLabel nameLabel = null, priceLabel = null, categoryLabel = null, imageLabel = null;
    JPanel panel = null;
    JButton deleteButton = null;

    switch (index) {
        case 0 -> { nameLabel = name1; priceLabel = price1; categoryLabel = category1; imageLabel = image1; panel = male1; deleteButton = delete1; }
        case 1 -> { nameLabel = name2; priceLabel = price2; categoryLabel = category2; imageLabel = image2; panel = male4; deleteButton = delete2; }
        case 2 -> { nameLabel = name3; priceLabel = price3; categoryLabel = category3; imageLabel = image3; panel = male5; deleteButton = delete3; }
        case 3 -> { nameLabel = name4; priceLabel = price4; categoryLabel = category4; imageLabel = image4; panel = male6; deleteButton = delete4; }
        case 4 -> { nameLabel = name5; priceLabel = price5; categoryLabel = category5; imageLabel = image5; panel = male7; deleteButton = delete5; }
        case 5 -> { nameLabel = name6; priceLabel = price6; categoryLabel = category6; imageLabel = image6; panel = male8; deleteButton = delete6; }
        case 6 -> { nameLabel = name7; priceLabel = price7; categoryLabel = category7; imageLabel = image7; panel = male9; deleteButton = delete7; }
        case 7 -> { nameLabel = name8; priceLabel = price8; categoryLabel = category8; imageLabel = image8; panel = male10; deleteButton = delete8; }
        case 8 -> { nameLabel = name9; priceLabel = price9; categoryLabel = category9; imageLabel = image9; panel = male11; deleteButton = delete9; }
    }

    if (nameLabel != null) {
        nameLabel.setText(name);
        priceLabel.setText(String.valueOf(price));
        categoryLabel.setText(category);
        if (image != null) {
            Image scaledImage = image.getScaledInstance(150, 150, Image.SCALE_SMOOTH);
            imageLabel.setIcon(new ImageIcon(scaledImage));
        } else {
            imageLabel.setIcon(null);
        }
        if (panel != null) panel.setVisible(true);
    }
    
    if (deleteButton != null) {
        removeAllActionListeners(deleteButton);
        deleteButton.addActionListener(e -> handleDelete(productId));
    }
}

    
    
    
    
    private void clearProductPanel(JPanel panel, JLabel name, JLabel price, JLabel category, JLabel image) {
        name.setText("");
        price.setText("");
        category.setText("");
        image.setIcon(null);
        panel.setVisible(false);
    }

    
    private void handleDelete(int productId) {
        int confirmation = JOptionPane.showConfirmDialog(this, "Are you sure you want to delete this product?", "Confirm Deletion", JOptionPane.YES_NO_OPTION);
        if (confirmation == JOptionPane.YES_OPTION) {
            
            boolean success = postDao.deleteProduct(productId);
            if (success) {
                JOptionPane.showMessageDialog(this, "Product deleted successfully!");
                displayAllProducts();  // Refresh UI
            } else {
                JOptionPane.showMessageDialog(this, "Failed to delete product.");
            }
        }
    }
    
    private void removeAllActionListeners(AbstractButton button) {
        for (java.awt.event.ActionListener al : button.getActionListeners()) {
            button.removeActionListener(al);
        }
    }


}
