/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package skydrop.view;
import javax.swing.*;


/**
 *
 * @author Suresh
 */
public class ProductPageView extends javax.swing.JFrame {

    /**
     * Creates new form ProductPageView
     */
    public ProductPageView() {
        initComponents();
        
        male1.setName("male");
        male2.setName("male");
        male3.setName("male");

        female1.setName("female");
        female2.setName("female");
        female3.setName("female");

    
        kids1.setName("kids");
        kids2.setName("kids");
        kids3.setName("kids");
        


    txtSearchField.getDocument().addDocumentListener(new javax.swing.event.DocumentListener() {
        public void insertUpdate(javax.swing.event.DocumentEvent e) {
            filterProducts();
        }
        public void removeUpdate(javax.swing.event.DocumentEvent e) {
            filterProducts();
        }
        public void changedUpdate(javax.swing.event.DocumentEvent e) {
            filterProducts();
        }
    });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtSearch = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        txtSearchField = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        Mcheckbox = new javax.swing.JCheckBox();
        Fcheckbox = new javax.swing.JCheckBox();
        Kcheckbox = new javax.swing.JCheckBox();
        jLabel5 = new javax.swing.JLabel();
        highlowbox = new javax.swing.JComboBox<>();
        ProductScrollPane = new javax.swing.JScrollPane();
        productGridPanel = new javax.swing.JPanel();
        male1 = new javax.swing.JPanel();
        btnBuyNow1M = new javax.swing.JButton();
        image1 = new javax.swing.JLabel();
        name1 = new javax.swing.JLabel();
        price1 = new javax.swing.JLabel();
        female1 = new javax.swing.JPanel();
        btnBuyNow2W = new javax.swing.JButton();
        lblImage2 = new javax.swing.JLabel();
        lblName1W = new javax.swing.JLabel();
        lblprice2 = new javax.swing.JLabel();
        kids1 = new javax.swing.JPanel();
        btnBuyNow3K = new javax.swing.JButton();
        lblImage3 = new javax.swing.JLabel();
        lblName1K = new javax.swing.JLabel();
        lblprice3 = new javax.swing.JLabel();
        male2 = new javax.swing.JPanel();
        btnBuyNow4M = new javax.swing.JButton();
        lblImage4 = new javax.swing.JLabel();
        lblName2M = new javax.swing.JLabel();
        lblprice4 = new javax.swing.JLabel();
        kids2 = new javax.swing.JPanel();
        btnBuyNow5K = new javax.swing.JButton();
        lblImage5 = new javax.swing.JLabel();
        lblName2K = new javax.swing.JLabel();
        lblprice5 = new javax.swing.JLabel();
        female2 = new javax.swing.JPanel();
        btnBuyNow6W = new javax.swing.JButton();
        lblImage6 = new javax.swing.JLabel();
        lblName2W = new javax.swing.JLabel();
        lblprice6 = new javax.swing.JLabel();
        male3 = new javax.swing.JPanel();
        btnBuyNow7M = new javax.swing.JButton();
        lblImage7 = new javax.swing.JLabel();
        lblName3M = new javax.swing.JLabel();
        lblprice7 = new javax.swing.JLabel();
        female3 = new javax.swing.JPanel();
        btnBuyNow8W = new javax.swing.JButton();
        lblImage8 = new javax.swing.JLabel();
        lblName3W = new javax.swing.JLabel();
        lblprice8 = new javax.swing.JLabel();
        kids3 = new javax.swing.JPanel();
        btnBuyNow9K = new javax.swing.JButton();
        lblImage9 = new javax.swing.JLabel();
        lblName3K = new javax.swing.JLabel();
        lblprice9 = new javax.swing.JLabel();
        btnback = new javax.swing.JButton();
        btnNext = new javax.swing.JButton();
        btnprevious = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setText("SkyDrop");

        txtSearch.setText("🔍");
        txtSearch.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        txtSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSearchActionPerformed(evt);
            }
        });

        jButton3.setText("🛒");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        jLabel3.setText(" Your Smart Shopping Partner");

        txtSearchField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSearchFieldActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(jLabel1))
                .addGap(321, 321, 321)
                .addComponent(txtSearchField, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(txtSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(17, 17, 17))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtSearchField, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(16, 16, 16))
        );

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel4.setText("Categories");

        Mcheckbox.setText("Male");
        Mcheckbox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                McheckboxActionPerformed(evt);
            }
        });

        Fcheckbox.setText("Female");
        Fcheckbox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FcheckboxActionPerformed(evt);
            }
        });

        Kcheckbox.setText("Kids");
        Kcheckbox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                KcheckboxActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Mcheckbox, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Fcheckbox, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Kcheckbox, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(Mcheckbox)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Fcheckbox)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Kcheckbox))
        );

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel5.setText("Price Range");

        highlowbox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Higher to Lower", "Lower to Higher", " " }));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(highlowbox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel5)
                    .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addContainerGap(57, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(highlowbox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(250, Short.MAX_VALUE))
        );

        ProductScrollPane.setViewportView(null);

        productGridPanel.setLayout(new java.awt.GridLayout(0, 3, 20, 20));

        male1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnBuyNow1M.setText("Buy now");
        btnBuyNow1M.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuyNow1MActionPerformed(evt);
            }
        });
        male1.add(btnBuyNow1M, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 241, -1, -1));
        male1.add(image1, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 6, 161, 149));

        name1.setText("name");
        male1.add(name1, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 173, 161, -1));

        price1.setText("price");
        male1.add(price1, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 207, -1, -1));

        productGridPanel.add(male1);

        female1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnBuyNow2W.setText("Buy now");
        btnBuyNow2W.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuyNow2WActionPerformed(evt);
            }
        });
        female1.add(btnBuyNow2W, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 241, -1, -1));

        lblImage2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/trial image.png"))); // NOI18N
        female1.add(lblImage2, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 6, 161, 149));

        lblName1W.setText("Women");
        female1.add(lblName1W, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 173, 161, -1));

        lblprice2.setText("$50");
        female1.add(lblprice2, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 207, -1, -1));

        productGridPanel.add(female1);

        kids1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnBuyNow3K.setText("Buy now");
        btnBuyNow3K.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuyNow3KActionPerformed(evt);
            }
        });
        kids1.add(btnBuyNow3K, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 241, -1, -1));

        lblImage3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/trial image.png"))); // NOI18N
        kids1.add(lblImage3, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 6, 161, 149));

        lblName1K.setText("kids");
        kids1.add(lblName1K, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 173, 161, -1));

        lblprice3.setText("$50");
        kids1.add(lblprice3, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 207, -1, -1));

        productGridPanel.add(kids1);

        male2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnBuyNow4M.setText("Buy now");
        btnBuyNow4M.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuyNow4MActionPerformed(evt);
            }
        });
        male2.add(btnBuyNow4M, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 241, -1, -1));

        lblImage4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/trial image.png"))); // NOI18N
        male2.add(lblImage4, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 6, 161, 149));

        lblName2M.setText("Men");
        male2.add(lblName2M, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 173, 161, -1));

        lblprice4.setText("$50");
        male2.add(lblprice4, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 207, -1, -1));

        productGridPanel.add(male2);

        kids2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnBuyNow5K.setText("Buy now");
        btnBuyNow5K.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuyNow5KActionPerformed(evt);
            }
        });
        kids2.add(btnBuyNow5K, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 241, -1, -1));

        lblImage5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/trial image.png"))); // NOI18N
        kids2.add(lblImage5, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 6, 161, 149));

        lblName2K.setText("Kids");
        kids2.add(lblName2K, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 173, 161, -1));

        lblprice5.setText("$50");
        kids2.add(lblprice5, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 207, -1, -1));

        productGridPanel.add(kids2);

        female2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnBuyNow6W.setText("Buy now");
        btnBuyNow6W.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuyNow6WActionPerformed(evt);
            }
        });
        female2.add(btnBuyNow6W, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 241, -1, -1));

        lblImage6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/trial image.png"))); // NOI18N
        female2.add(lblImage6, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 6, 161, 149));

        lblName2W.setText("Women");
        female2.add(lblName2W, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 173, 161, -1));

        lblprice6.setText("$50");
        female2.add(lblprice6, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 207, -1, -1));

        productGridPanel.add(female2);

        male3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnBuyNow7M.setText("Buy now");
        btnBuyNow7M.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuyNow7MActionPerformed(evt);
            }
        });
        male3.add(btnBuyNow7M, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 241, -1, -1));

        lblImage7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/trial image.png"))); // NOI18N
        male3.add(lblImage7, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 6, 161, 149));

        lblName3M.setText("Men");
        male3.add(lblName3M, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 173, 161, -1));

        lblprice7.setText("$50");
        male3.add(lblprice7, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 207, -1, -1));

        productGridPanel.add(male3);

        female3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnBuyNow8W.setText("Buy now");
        btnBuyNow8W.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuyNow8WActionPerformed(evt);
            }
        });
        female3.add(btnBuyNow8W, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 241, -1, -1));

        lblImage8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/trial image.png"))); // NOI18N
        female3.add(lblImage8, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 6, 161, 149));

        lblName3W.setText("Women");
        female3.add(lblName3W, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 173, 161, -1));

        lblprice8.setText("$50");
        female3.add(lblprice8, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 207, -1, -1));

        productGridPanel.add(female3);

        kids3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnBuyNow9K.setText("Buy now");
        btnBuyNow9K.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuyNow9KActionPerformed(evt);
            }
        });
        kids3.add(btnBuyNow9K, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 241, -1, -1));

        lblImage9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/trial image.png"))); // NOI18N
        kids3.add(lblImage9, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 6, 161, 149));

        lblName3K.setText("Kids");
        kids3.add(lblName3K, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 173, 161, -1));

        lblprice9.setText("$50");
        kids3.add(lblprice9, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 207, -1, -1));

        productGridPanel.add(kids3);

        ProductScrollPane.setViewportView(productGridPanel);

        btnback.setText("Back");
        btnback.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnbackActionPerformed(evt);
            }
        });

        btnNext.setText("Next");

        btnprevious.setText("previous");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnback))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnprevious)
                        .addGap(431, 431, 431)
                        .addComponent(btnNext))
                    .addComponent(ProductScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 578, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(ProductScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnback)
                    .addComponent(btnNext)
                    .addComponent(btnprevious))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSearchActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSearchActionPerformed

    private void McheckboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_McheckboxActionPerformed
        // TODO add your handling code here:
        filterProducts();
    }//GEN-LAST:event_McheckboxActionPerformed

    private void btnBuyNow1MActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuyNow1MActionPerformed
         // TODO add your handling code here:
    }//GEN-LAST:event_btnBuyNow1MActionPerformed

    private void btnBuyNow2WActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuyNow2WActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnBuyNow2WActionPerformed

    private void btnBuyNow3KActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuyNow3KActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnBuyNow3KActionPerformed

    private void btnBuyNow4MActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuyNow4MActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnBuyNow4MActionPerformed

    private void btnBuyNow5KActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuyNow5KActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnBuyNow5KActionPerformed

    private void btnBuyNow6WActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuyNow6WActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnBuyNow6WActionPerformed

    private void btnBuyNow7MActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuyNow7MActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnBuyNow7MActionPerformed

    private void btnBuyNow8WActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuyNow8WActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnBuyNow8WActionPerformed

    private void btnBuyNow9KActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuyNow9KActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnBuyNow9KActionPerformed

    private void btnbackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnbackActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnbackActionPerformed

    private void FcheckboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FcheckboxActionPerformed
        // TODO add your handling code here:
        filterProducts();
    }//GEN-LAST:event_FcheckboxActionPerformed

    private void KcheckboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_KcheckboxActionPerformed
        // TODO add your handling code here:
        filterProducts();
    }//GEN-LAST:event_KcheckboxActionPerformed

    private void txtSearchFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSearchFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSearchFieldActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ProductPageView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ProductPageView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ProductPageView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ProductPageView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ProductPageView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox Fcheckbox;
    private javax.swing.JCheckBox Kcheckbox;
    private javax.swing.JCheckBox Mcheckbox;
    private javax.swing.JScrollPane ProductScrollPane;
    private javax.swing.JButton btnBuyNow1M;
    private javax.swing.JButton btnBuyNow2W;
    private javax.swing.JButton btnBuyNow3K;
    private javax.swing.JButton btnBuyNow4M;
    private javax.swing.JButton btnBuyNow5K;
    private javax.swing.JButton btnBuyNow6W;
    private javax.swing.JButton btnBuyNow7M;
    private javax.swing.JButton btnBuyNow8W;
    private javax.swing.JButton btnBuyNow9K;
    private javax.swing.JButton btnNext;
    private javax.swing.JButton btnback;
    private javax.swing.JButton btnprevious;
    private javax.swing.JPanel female1;
    private javax.swing.JPanel female2;
    private javax.swing.JPanel female3;
    private javax.swing.JComboBox<String> highlowbox;
    private javax.swing.JLabel image1;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel kids1;
    private javax.swing.JPanel kids2;
    private javax.swing.JPanel kids3;
    private javax.swing.JLabel lblImage2;
    private javax.swing.JLabel lblImage3;
    private javax.swing.JLabel lblImage4;
    private javax.swing.JLabel lblImage5;
    private javax.swing.JLabel lblImage6;
    private javax.swing.JLabel lblImage7;
    private javax.swing.JLabel lblImage8;
    private javax.swing.JLabel lblImage9;
    private javax.swing.JLabel lblName1K;
    private javax.swing.JLabel lblName1W;
    private javax.swing.JLabel lblName2K;
    private javax.swing.JLabel lblName2M;
    private javax.swing.JLabel lblName2W;
    private javax.swing.JLabel lblName3K;
    private javax.swing.JLabel lblName3M;
    private javax.swing.JLabel lblName3W;
    private javax.swing.JLabel lblprice2;
    private javax.swing.JLabel lblprice3;
    private javax.swing.JLabel lblprice4;
    private javax.swing.JLabel lblprice5;
    private javax.swing.JLabel lblprice6;
    private javax.swing.JLabel lblprice7;
    private javax.swing.JLabel lblprice8;
    private javax.swing.JLabel lblprice9;
    private javax.swing.JPanel male1;
    private javax.swing.JPanel male2;
    private javax.swing.JPanel male3;
    private javax.swing.JLabel name1;
    private javax.swing.JLabel price1;
    private javax.swing.JPanel productGridPanel;
    private javax.swing.JButton txtSearch;
    private javax.swing.JTextField txtSearchField;
    // End of variables declaration//GEN-END:variables
    private void filterProducts() {
        boolean showMale = Mcheckbox.isSelected();
        boolean showFemale = Fcheckbox.isSelected();
        boolean showKids = Kcheckbox.isSelected();

        String searchText = txtSearchField.getText().trim().toLowerCase(); // Correct JTextField

        JPanel[] allProducts = {
            male1, male2, male3,
            female1, female2, female3,
            kids1, kids2, kids3
        };

        boolean anyCategorySelected = showMale || showFemale || showKids;

        for (JPanel panel : allProducts) {
            String category = panel.getName();

            JLabel label = (JLabel) panel.getComponent(2); // Adjust index if needed
            String productName = label.getText().toLowerCase();

            boolean matchesCategory = !anyCategorySelected ||
                (showMale && category.equals("male")) ||
                (showFemale && category.equals("female")) ||
                (showKids && category.equals("kids"));

            boolean matchesSearch = productName.contains(searchText);

            panel.setVisible(matchesCategory && matchesSearch);
        }

        revalidate();
        repaint();
    }   





}
