/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package skydrop.view;
import java.awt.Image;
import javax.swing.*;
import skydrop.userDAO.PostDao;


/**
 *
 * @author Suresh
 */
public class ProductPageView extends javax.swing.JFrame {

    PostDao postDao = new PostDao();
    /**
     * Creates new form ProductPageView
     */
    public ProductPageView() {
        initComponents();
        displayAllProducts();
        


    txtSearchField.getDocument().addDocumentListener(new javax.swing.event.DocumentListener() {
        public void insertUpdate(javax.swing.event.DocumentEvent e) {
            filterProducts();
        }
        public void removeUpdate(javax.swing.event.DocumentEvent e) {
            filterProducts();
        }
        public void changedUpdate(javax.swing.event.DocumentEvent e) {
            filterProducts();
        }
    });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtSearch = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        txtSearchField = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        Mcheckbox = new javax.swing.JCheckBox();
        Fcheckbox = new javax.swing.JCheckBox();
        Kcheckbox = new javax.swing.JCheckBox();
        jLabel5 = new javax.swing.JLabel();
        highlowbox = new javax.swing.JComboBox<>();
        ProductScrollPane = new javax.swing.JScrollPane();
        productGridPanel = new javax.swing.JPanel();
        male1 = new javax.swing.JPanel();
        btnBuyNow1M = new javax.swing.JButton();
        image1 = new javax.swing.JLabel();
        category1 = new javax.swing.JLabel();
        price1 = new javax.swing.JLabel();
        name1 = new javax.swing.JLabel();
        male4 = new javax.swing.JPanel();
        btnBuyNow1M1 = new javax.swing.JButton();
        image2 = new javax.swing.JLabel();
        category2 = new javax.swing.JLabel();
        price2 = new javax.swing.JLabel();
        name2 = new javax.swing.JLabel();
        male5 = new javax.swing.JPanel();
        btnBuyNow1M2 = new javax.swing.JButton();
        image3 = new javax.swing.JLabel();
        category3 = new javax.swing.JLabel();
        price3 = new javax.swing.JLabel();
        name3 = new javax.swing.JLabel();
        male6 = new javax.swing.JPanel();
        btnBuyNow1M3 = new javax.swing.JButton();
        image4 = new javax.swing.JLabel();
        category4 = new javax.swing.JLabel();
        price4 = new javax.swing.JLabel();
        name4 = new javax.swing.JLabel();
        male7 = new javax.swing.JPanel();
        btnBuyNow1M4 = new javax.swing.JButton();
        image5 = new javax.swing.JLabel();
        category5 = new javax.swing.JLabel();
        price5 = new javax.swing.JLabel();
        name5 = new javax.swing.JLabel();
        male8 = new javax.swing.JPanel();
        btnBuyNow1M5 = new javax.swing.JButton();
        image6 = new javax.swing.JLabel();
        category6 = new javax.swing.JLabel();
        price6 = new javax.swing.JLabel();
        name6 = new javax.swing.JLabel();
        male9 = new javax.swing.JPanel();
        btnBuyNow1M6 = new javax.swing.JButton();
        image7 = new javax.swing.JLabel();
        category7 = new javax.swing.JLabel();
        price7 = new javax.swing.JLabel();
        name7 = new javax.swing.JLabel();
        male10 = new javax.swing.JPanel();
        btnBuyNow1M7 = new javax.swing.JButton();
        image8 = new javax.swing.JLabel();
        category8 = new javax.swing.JLabel();
        price8 = new javax.swing.JLabel();
        name8 = new javax.swing.JLabel();
        male11 = new javax.swing.JPanel();
        btnBuyNow1M8 = new javax.swing.JButton();
        image9 = new javax.swing.JLabel();
        category9 = new javax.swing.JLabel();
        price9 = new javax.swing.JLabel();
        name9 = new javax.swing.JLabel();
        btnback = new javax.swing.JButton();
        btnNext = new javax.swing.JButton();
        btnprevious = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setText("SkyDrop");

        txtSearch.setText("🔍");
        txtSearch.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        txtSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSearchActionPerformed(evt);
            }
        });

        jButton3.setText("🛒");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        jLabel3.setText(" Your Smart Shopping Partner");

        txtSearchField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSearchFieldActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(jLabel1))
                .addGap(321, 321, 321)
                .addComponent(txtSearchField, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(txtSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(17, 17, 17))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtSearchField, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(16, 16, 16))
        );

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel4.setText("Categories");

        Mcheckbox.setText("Male");
        Mcheckbox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                McheckboxActionPerformed(evt);
            }
        });

        Fcheckbox.setText("Female");
        Fcheckbox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FcheckboxActionPerformed(evt);
            }
        });

        Kcheckbox.setText("Kids");
        Kcheckbox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                KcheckboxActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Mcheckbox, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Fcheckbox, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Kcheckbox, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(Mcheckbox)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Fcheckbox)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Kcheckbox))
        );

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel5.setText("Price Range");

        highlowbox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Higher to Lower", "Lower to Higher", " " }));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(highlowbox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel5)
                    .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addContainerGap(57, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(highlowbox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(250, Short.MAX_VALUE))
        );

        ProductScrollPane.setViewportView(null);

        productGridPanel.setLayout(new java.awt.GridLayout(0, 3, 20, 20));

        male1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnBuyNow1M.setText("Buy now");
        btnBuyNow1M.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuyNow1MActionPerformed(evt);
            }
        });
        male1.add(btnBuyNow1M, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 241, -1, -1));
        male1.add(image1, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 6, 161, 149));

        category1.setText("men");
        male1.add(category1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 200, 40, -1));

        price1.setText("price");
        male1.add(price1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 200, -1, -1));

        name1.setText("name");
        male1.add(name1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 170, -1, -1));

        productGridPanel.add(male1);

        male4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnBuyNow1M1.setText("Buy now");
        btnBuyNow1M1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuyNow1M1ActionPerformed(evt);
            }
        });
        male4.add(btnBuyNow1M1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 241, -1, -1));
        male4.add(image2, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 6, 161, 149));

        category2.setText("men");
        male4.add(category2, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 200, 40, -1));

        price2.setText("price");
        male4.add(price2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 200, -1, -1));

        name2.setText("name");
        male4.add(name2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 170, -1, -1));

        productGridPanel.add(male4);

        male5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnBuyNow1M2.setText("Buy now");
        btnBuyNow1M2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuyNow1M2ActionPerformed(evt);
            }
        });
        male5.add(btnBuyNow1M2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 241, -1, -1));
        male5.add(image3, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 6, 161, 149));

        category3.setText("men");
        male5.add(category3, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 200, 40, -1));

        price3.setText("price");
        male5.add(price3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 200, -1, -1));

        name3.setText("name");
        male5.add(name3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 170, -1, -1));

        productGridPanel.add(male5);

        male6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnBuyNow1M3.setText("Buy now");
        btnBuyNow1M3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuyNow1M3ActionPerformed(evt);
            }
        });
        male6.add(btnBuyNow1M3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 241, -1, -1));
        male6.add(image4, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 6, 161, 149));

        category4.setText("men");
        male6.add(category4, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 200, 40, -1));

        price4.setText("price");
        male6.add(price4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 200, -1, -1));

        name4.setText("name");
        male6.add(name4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 170, -1, -1));

        productGridPanel.add(male6);

        male7.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnBuyNow1M4.setText("Buy now");
        btnBuyNow1M4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuyNow1M4ActionPerformed(evt);
            }
        });
        male7.add(btnBuyNow1M4, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 241, -1, -1));
        male7.add(image5, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 6, 161, 149));

        category5.setText("men");
        male7.add(category5, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 200, 40, -1));

        price5.setText("price");
        male7.add(price5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 200, -1, -1));

        name5.setText("name");
        male7.add(name5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 170, -1, -1));

        productGridPanel.add(male7);

        male8.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnBuyNow1M5.setText("Buy now");
        btnBuyNow1M5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuyNow1M5ActionPerformed(evt);
            }
        });
        male8.add(btnBuyNow1M5, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 241, -1, -1));
        male8.add(image6, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 6, 161, 149));

        category6.setText("men");
        male8.add(category6, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 200, 40, -1));

        price6.setText("price");
        male8.add(price6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 200, -1, -1));

        name6.setText("name");
        male8.add(name6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 170, -1, -1));

        productGridPanel.add(male8);

        male9.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnBuyNow1M6.setText("Buy now");
        btnBuyNow1M6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuyNow1M6ActionPerformed(evt);
            }
        });
        male9.add(btnBuyNow1M6, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 241, -1, -1));
        male9.add(image7, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 6, 161, 149));

        category7.setText("men");
        male9.add(category7, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 200, 40, -1));

        price7.setText("price");
        male9.add(price7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 200, -1, -1));

        name7.setText("name");
        male9.add(name7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 170, -1, -1));

        productGridPanel.add(male9);

        male10.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnBuyNow1M7.setText("Buy now");
        btnBuyNow1M7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuyNow1M7ActionPerformed(evt);
            }
        });
        male10.add(btnBuyNow1M7, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 241, -1, -1));
        male10.add(image8, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 6, 161, 149));

        category8.setText("men");
        male10.add(category8, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 200, 40, -1));

        price8.setText("price");
        male10.add(price8, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 200, -1, -1));

        name8.setText("name");
        male10.add(name8, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 170, -1, -1));

        productGridPanel.add(male10);

        male11.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnBuyNow1M8.setText("Buy now");
        btnBuyNow1M8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuyNow1M8ActionPerformed(evt);
            }
        });
        male11.add(btnBuyNow1M8, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 241, -1, -1));
        male11.add(image9, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 6, 161, 149));

        category9.setText("men");
        male11.add(category9, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 200, 40, -1));

        price9.setText("price");
        male11.add(price9, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 200, -1, -1));

        name9.setText("name");
        male11.add(name9, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 170, -1, -1));

        productGridPanel.add(male11);

        ProductScrollPane.setViewportView(productGridPanel);

        btnback.setText("Back");
        btnback.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnbackActionPerformed(evt);
            }
        });

        btnNext.setText("Next");

        btnprevious.setText("previous");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnback))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnprevious)
                        .addGap(431, 431, 431)
                        .addComponent(btnNext))
                    .addComponent(ProductScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 578, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(ProductScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnback)
                    .addComponent(btnNext)
                    .addComponent(btnprevious))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSearchActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSearchActionPerformed

    private void McheckboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_McheckboxActionPerformed
        // TODO add your handling code here:
        filterProducts();
    }//GEN-LAST:event_McheckboxActionPerformed

    private void btnBuyNow1MActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuyNow1MActionPerformed
         // TODO add your handling code here:
    }//GEN-LAST:event_btnBuyNow1MActionPerformed

    private void btnbackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnbackActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnbackActionPerformed

    private void FcheckboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FcheckboxActionPerformed
        // TODO add your handling code here:
        filterProducts();
    }//GEN-LAST:event_FcheckboxActionPerformed

    private void KcheckboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_KcheckboxActionPerformed
        // TODO add your handling code here:
        filterProducts();
    }//GEN-LAST:event_KcheckboxActionPerformed

    private void txtSearchFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSearchFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSearchFieldActionPerformed

    private void btnBuyNow1M1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuyNow1M1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnBuyNow1M1ActionPerformed

    private void btnBuyNow1M2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuyNow1M2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnBuyNow1M2ActionPerformed

    private void btnBuyNow1M3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuyNow1M3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnBuyNow1M3ActionPerformed

    private void btnBuyNow1M4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuyNow1M4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnBuyNow1M4ActionPerformed

    private void btnBuyNow1M5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuyNow1M5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnBuyNow1M5ActionPerformed

    private void btnBuyNow1M6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuyNow1M6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnBuyNow1M6ActionPerformed

    private void btnBuyNow1M7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuyNow1M7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnBuyNow1M7ActionPerformed

    private void btnBuyNow1M8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuyNow1M8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnBuyNow1M8ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ProductPageView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ProductPageView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ProductPageView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ProductPageView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ProductPageView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox Fcheckbox;
    private javax.swing.JCheckBox Kcheckbox;
    private javax.swing.JCheckBox Mcheckbox;
    private javax.swing.JScrollPane ProductScrollPane;
    private javax.swing.JButton btnBuyNow1M;
    private javax.swing.JButton btnBuyNow1M1;
    private javax.swing.JButton btnBuyNow1M2;
    private javax.swing.JButton btnBuyNow1M3;
    private javax.swing.JButton btnBuyNow1M4;
    private javax.swing.JButton btnBuyNow1M5;
    private javax.swing.JButton btnBuyNow1M6;
    private javax.swing.JButton btnBuyNow1M7;
    private javax.swing.JButton btnBuyNow1M8;
    private javax.swing.JButton btnNext;
    private javax.swing.JButton btnback;
    private javax.swing.JButton btnprevious;
    private javax.swing.JLabel category1;
    private javax.swing.JLabel category2;
    private javax.swing.JLabel category3;
    private javax.swing.JLabel category4;
    private javax.swing.JLabel category5;
    private javax.swing.JLabel category6;
    private javax.swing.JLabel category7;
    private javax.swing.JLabel category8;
    private javax.swing.JLabel category9;
    private javax.swing.JComboBox<String> highlowbox;
    private javax.swing.JLabel image1;
    private javax.swing.JLabel image2;
    private javax.swing.JLabel image3;
    private javax.swing.JLabel image4;
    private javax.swing.JLabel image5;
    private javax.swing.JLabel image6;
    private javax.swing.JLabel image7;
    private javax.swing.JLabel image8;
    private javax.swing.JLabel image9;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel male1;
    private javax.swing.JPanel male10;
    private javax.swing.JPanel male11;
    private javax.swing.JPanel male4;
    private javax.swing.JPanel male5;
    private javax.swing.JPanel male6;
    private javax.swing.JPanel male7;
    private javax.swing.JPanel male8;
    private javax.swing.JPanel male9;
    private javax.swing.JLabel name1;
    private javax.swing.JLabel name2;
    private javax.swing.JLabel name3;
    private javax.swing.JLabel name4;
    private javax.swing.JLabel name5;
    private javax.swing.JLabel name6;
    private javax.swing.JLabel name7;
    private javax.swing.JLabel name8;
    private javax.swing.JLabel name9;
    private javax.swing.JLabel price1;
    private javax.swing.JLabel price2;
    private javax.swing.JLabel price3;
    private javax.swing.JLabel price4;
    private javax.swing.JLabel price5;
    private javax.swing.JLabel price6;
    private javax.swing.JLabel price7;
    private javax.swing.JLabel price8;
    private javax.swing.JLabel price9;
    private javax.swing.JPanel productGridPanel;
    private javax.swing.JButton txtSearch;
    private javax.swing.JTextField txtSearchField;
    // End of variables declaration//GEN-END:variables
    private void filterProducts() {
        boolean showMale = Mcheckbox.isSelected();
        boolean showFemale = Fcheckbox.isSelected();
        boolean showKids = Kcheckbox.isSelected();

        String searchText = txtSearchField.getText().trim().toLowerCase(); // Correct JTextField

//        JPanel[] allProducts = {
//            male1, male2, male3,
//            female1, female2, female3,
//            kids1, kids2, kids3
//        };

        boolean anyCategorySelected = showMale || showFemale || showKids;

//        for (JPanel panel : allProducts) {
//            String category = panel.getName();
//
//            JLabel label = (JLabel) panel.getComponent(2); // Adjust index if needed
//            String productName = label.getText().toLowerCase();
//
//            boolean matchesCategory = !anyCategorySelected ||
//                (showMale && category.equals("male")) ||
//                (showFemale && category.equals("female")) ||
//                (showKids && category.equals("kids"));
//
//            boolean matchesSearch = productName.contains(searchText);
//
//            panel.setVisible(matchesCategory && matchesSearch);
//        }
//
//        revalidate();
//        repaint();
    }   

    private void displayAllProducts() {
        displayProduct(1, name1, price1, category1, image1);
        displayProduct(2, name2, price2, category2, image2);
        displayProduct(3, name3, price3, category3, image3);
        displayProduct(4, name4, price4, category4, image4);
        displayProduct(5, name5, price5, category5, image5);
        displayProduct(6, name6, price6, category6, image6);
        displayProduct(7, name7, price7, category7, image7);
        displayProduct(8, name8, price8, category8, image8);
        displayProduct(9, name9, price9, category9, image9);
    }

    private void displayProduct(int i, JLabel nameLabel, JLabel priceLabel, JLabel categoryLabel, JLabel imageLabel) {
        String name = postDao.getProductNameDB(i);
        int price = postDao.getProductPriceDB(i);
        String category = postDao.getProductCategoryDB(i);
        Image image = postDao.displayImageFromDatabase(i);

        nameLabel.setText(name != null ? name : "No Name");
        priceLabel.setText(price >= 0 ? String.valueOf(price) : "N/A");
        categoryLabel.setText(category != null ? category : "N/A");

        if (image != null) {
            imageLabel.setIcon(new ImageIcon(image));
            imageLabel.setText("");
        } else {
            imageLabel.setIcon(null);
        }
    }



}
